=== rok4/styles/style.202012.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "title": "ROK4 Style",
    "type": "object",
    "properties": {
        "identifier": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "abstract": {
            "type": "string"
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "legend": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                },
                "min_scale_denominator": {
                    "type": "integer"
                },
                "max_scale_denominator": {
                    "type": "integer"
                }
            }
        },
        "exposition": {
            "type": "object",
            "properties": {
                "algo": {
                    "type": "string",
                    "enum": ["H"]
                },
                "min_slope": {
                    "type": "integer"
                }
            }
        },
        "estompage": {
            "type": "object",
            "properties": {
                "interpolation": {
                    "type": "string"
                },
                "zenith": {
                    "type": "number"
                },
                "azimuth": {
                    "type": "number"
                },
                "z_factor": {
                    "type": "number"
                }
            }
        },
        "pente": {
            "type": "object",
            "properties": {
                "algo": {
                    "type": "string",
                    "enum": ["H"]
                },
                "unit": {
                    "type": "string"
                },
                "interpolation": {
                    "type": "string"
                },
                "image_nodata": {
                    "type": "number"
                },
                "slope_nodata": {
                    "type": "number"
                },
                "slope_max": {
                    "type": "number"
                }
            }
        },
        "palette": {
            "type": "object",
            "properties": {
                "rgb_continuous": {
                    "type": "boolean"
                },
                "alpha_continuous": {
                    "type": "boolean"
                },
                "max_value": {
                    "type": "number"
                },
                "colours": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "value": {
                                "type": "number"
                            },
                            "red": {
                                "type": "integer"
                            },
                            "green": {
                                "type": "integer"
                            },
                            "blue": {
                                "type": "integer"
                            },
                            "alpha": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== rok4/styles/inspire.json
{
	"identifier": "DEFAULT",
    "title": "Style INSPIRE",
	"abstract": "Style sans transformation INSPIRE",
	"keywords": ["Défaut", "INSPIRE"],
    "legend": {
        "format": "image/png",
        "url": "http://ign.fr/inspire",
        "height": 100,
        "width": 100,
        "min_scale_denominator": 0,
        "max_scale_denominator": 30
    }
}

=== rok4/styles/pente.json
{
	"identifier": "pente",
    "title": "Pente",
	"abstract": "Pente calculee avec la methode de Horn",
	"keywords": ["MNT"],
    "legend": {
        "format": "image/png",
        "url": "http://ign.fr",
        "height": 100,
        "width": 100,
        "min_scale_denominator": 0,
        "max_scale_denominator": 30
    },
    "pente": {
        "algo": "H",
        "unit": "degree",
        "interpolation": "linear",
        "image_nodata": -99999,
        "slope_nodata": 91,
        "slope_max": 90
    }
}

=== rok4/styles/montagne_palette.json
{
	"identifier": "montagne_palette",
    "title": "Pente par paliers standards",
	"abstract": "Pente affich√©e par parlier standard de 30 a 90 degres",
	"keywords": ["MNT"],
    "legend": {
        "format": "image/png",
        "url": "http://ign.fr",
        "height": 100,
        "width": 100,
        "min_scale_denominator": 0,
        "max_scale_denominator": 30
    },
    "palette": {
        "no_alpha": false,
        "rgb_continuous": true,
        "alpha_continuous": true,
        "colours": [
            { "value": 0, "red": 255, "green": 255, "blue": 255, "alpha": 0 },
            { "value": 29, "red": 255, "green": 255, "blue": 255, "alpha": 0 },
            { "value": 30, "red": 242, "green": 229, "blue": 0, "alpha": 255 },
            { "value": 34, "red": 242, "green": 229, "blue": 0, "alpha": 255 },
            { "value": 35, "red": 243, "green": 148, "blue": 25, "alpha": 255 },
            { "value": 39, "red": 243, "green": 148, "blue": 25, "alpha": 255 },
            { "value": 40, "red": 225, "green": 0, "blue": 0, "alpha": 255 },
            { "value": 44, "red": 225, "green": 0, "blue": 0, "alpha": 255 },
            { "value": 45, "red": 200, "green": 137, "blue": 187, "alpha": 255 },
            { "value": 90, "red": 200, "green": 137, "blue": 187, "alpha": 255 },
            { "value": 91, "red": 255, "green": 255, "blue": 255, "alpha": 0 }
        ]
    }
}

=== rok4/styles/estompage.json
{
    "identifier": "estompage",
    "title": "Estompage",
    "abstract": "Estompage Azimuth 315Â°",
    "keywords": ["MNT"],
    "legend": {
        "format": "image/png",
        "url": "http://ign.fr",
        "height": 100,
        "width": 100,
        "min_scale_denominator": 0,
        "max_scale_denominator": 30
    },
    "estompage": {
        "zenith": 45,
        "azimuth": 315,
        "z_factor": 1,
        "interpolation": "linear"
    },
    "palette": {
        "no_alpha": false,
        "rgb_continuous": true,
        "alpha_continuous": true,
        "colours": [
            { "value": 0, "red": 0, "green": 0, "blue": 0, "alpha": 64 },
            { "value": 255, "red": 255, "green": 255, "blue": 255, "alpha": 64 }
        ]
    }
}

=== rok4/styles/aspect.json
{
	"identifier": "aspect",
    "title": "Aspect",
	"abstract": "Calcul de l'exposition par la m√©thode de Horn",
	"keywords": ["MNT"],
    "legend": {
        "format": "image/png",
        "url": "http://ign.fr",
        "height": 100,
        "width": 100,
        "min_scale_denominator": 0,
        "max_scale_denominator": 30
    },
    "exposition": {
        "algo": "H",
        "min_slope": 1
    },
    "palette": {
        "rgb_continuous": true,
        "alpha_continuous": true,
        "no_alpha": false,
        "colours": [
            { "value": -1.0, "red": 255, "green": 255, "blue": 255, "alpha": 0 },
            { "value": 0, "red": 224, "green": 32, "blue": 29, "alpha": 200 },
            { "value": 22.5, "red": 224, "green": 32, "blue": 29, "alpha": 200 },
            { "value": 22.6, "red": 230, "green": 142, "blue": 28, "alpha": 200 },
            { "value": 67.5, "red": 230, "green": 142, "blue": 28, "alpha": 200 },
            { "value": 67.6, "red": 255, "green": 112, "blue": 18, "alpha": 200 },
            { "value": 112.5, "red": 255, "green": 112, "blue": 18, "alpha": 200 },
            { "value": 112.6, "red": 219, "green": 199, "blue": 14, "alpha": 200 },
            { "value": 157.5, "red": 219, "green": 199, "blue": 14, "alpha": 200 },
            { "value": 157.6, "red": 11, "green": 215, "blue": 230, "alpha": 200 },
            { "value": 202.5, "red": 11, "green": 215, "blue": 230, "alpha": 200 },
            { "value": 202.6, "red": 14, "green": 113, "blue": 199, "alpha": 200 },
            { "value": 247.5, "red": 14, "green": 113, "blue": 199, "alpha": 200 },
            { "value": 247.6, "red": 50, "green": 50, "blue": 235, "alpha": 200 },
            { "value": 292.5, "red": 50, "green": 50, "blue": 235, "alpha": 200 },
            { "value": 292.6, "red": 222, "green": 27, "blue": 141, "alpha": 200 },
            { "value": 337.5, "red": 222, "green": 27, "blue": 141, "alpha": 200 },
            { "value": 337.6, "red": 224, "green": 32, "blue": 29, "alpha": 200 },
            { "value": 360.0, "red": 224, "green": 32, "blue": 29, "alpha": 200 }
        ]
    }
}

=== rok4/styles/normal.json
{
	"identifier": "normal",
    "title": "Données brutes",
	"abstract": "Données brutes, sans modification de canal",
	"keywords": ["Défaut"],
    "legend": {
        "format": "image/jpeg",
        "url": "https://data.geopf.fr/annexes/ressources/legendes/LEGEND.jpg",
        "height": 69,
        "width": 280,
        "min_scale_denominator": 200,
        "max_scale_denominator": 100000000
    }
}

=== rok4/styles/orange.json
{
	"identifier": "orange",
    "title": "Palette orange - transparent",
	"abstract": "Orange sur fond transparent",
	"keywords": ["orange", "transparent"],
    "legend": {
        "format": "image/png",
        "url": "http://ign.fr",
        "height": 100,
        "width": 100,
        "min_scale_denominator": 0,
        "max_scale_denominator": 999999
    },
    "palette": {
        "no_alpha": false,
        "rgb_continuous": true,
        "alpha_continuous": true,
        "colours": [
            { "value": 0, "red": 255, "green": 132, "blue": 0, "alpha": 255 },
            { "value": 200, "red": 255, "green": 132, "blue": 0, "alpha": 55 },
            { "value": 255, "red": 255, "green": 255, "blue": 255, "alpha": 0 }
        ]
    }
}

=== rok4/styles/hypso.json
{
	"identifier": "hypso",
    "title": "Teinte Hypsométrique",
	"abstract": "Teinte Hypsométrique",
	"keywords": ["MNT"],
    "legend": {
        "format": "image/png",
        "url": "http://ign.fr",
        "height": 100,
        "width": 100,
        "min_scale_denominator": 0,
        "max_scale_denominator": 30
    },
    "palette": {
        "no_alpha": false,
        "rgb_continuous": true,
        "alpha_continuous": true,
        "colours": [
            { "value": -99999, "red": 255, "green": 255, "blue": 255, "alpha": 0 },
            { "value": -99998.1, "red": 255, "green": 255, "blue": 255, "alpha": 0 },
            { "value": -99998.0, "red": 255, "green": 0, "blue": 255, "alpha": 255 },
            { "value": -501, "red": 255, "green": 0, "blue": 255, "alpha": 255 },
            { "value": -500, "red": 1, "green": 29, "blue": 148, "alpha": 255 },
            { "value": -15, "red": 19, "green": 42, "blue": 255, "alpha": 255 },
            { "value": 0, "red": 67, "green": 105, "blue": 227, "alpha": 255 },
            { "value": 0.01, "red": 57, "green": 151, "blue": 105, "alpha": 255 },
            { "value": 300, "red": 230, "green": 230, "blue": 128, "alpha": 255 },
            { "value": 600, "red": 220, "green": 179, "blue": 99, "alpha": 255 },
            { "value": 2000, "red": 162, "green": 100, "blue": 51, "alpha": 255 },
            { "value": 2500, "red": 122, "green": 81, "blue": 40, "alpha": 255 },
            { "value": 3000, "red": 255, "green": 255, "blue": 255, "alpha": 255 },
            { "value": 9000, "red": 255, "green": 255, "blue": 255, "alpha": 255 },
            { "value": 9001, "red": 255, "green": 255, "blue": 255, "alpha": 255 }
        ]
    }
}
